### PR TITLE
test: Add detox with a simple e2e test

### LINKED ISSUE #19: Add E2E tests using some automated simulator
It all started as a weekend project, so I didn't write tests.

Now people are starting to use this app, so it would be wise to make it a serious project.

### PR DESCRIPTION
**Pull request by amaurymartiny**
fixes #19 

blocked by the same issue as https://github.com/yaron1m/expo-detox-typescript-example/issues/5

Quickstart:
1. run `./e2e/dl_expo_bins.sh`
2. run `yarn start`, spawn up the ios simulator
3. in another terminal, run `yarn test:e2e`

### CODE REVIEW

**Comment by frankcalise** [comment]
Any luck with this lately?

**Comment by amaurymartiny** [comment]
No, still blocked... Would appreciate help on this one

**Comment by frankcalise** [comment]
Yeah I'm struggling with it also. What have you tried? Latest detox as well? Are you trying Android emulator or iOS sim?

**Comment by amaurymartiny** [comment]
What I tried is in this PR: latest detox (or almost latest, not sure) + ios simulator

**Comment by frankcalise** [comment]
Any success?

**Pull request merged**
